logFile: 
  accessLogPath: "./access.log"
  errorLogPath: "./error.log"
  maxSize: 500

jwt:
  secretKey: "jwt_secret_key"

snowflake:
  // machine id between 0 to 1023
  machineID: 1

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "toor"
  db: "go_forum"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0