logFile: 
  accessLogPath: "./access.log"
  errorLogPath: "./error.log"
  maxSize: 500

jwt:
  secretKey: "jwt_secret_key"

mysql:
  user: "root"
  password: "toor"
  host: "localhost"
  port: 3306
  db: "mysql"