definitions:
  model.Registration:
    properties:
      confirm:
        example: PaSsWoRd
        type: string
      name:
        example: Username
        type: string
      password:
        example: PaSsWoRd
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth/sign-up:
    post:
      consumes:
      - application/json
      parameters:
      - description: registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Registration'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: user sign up
      tags:
      - auth
swagger: "2.0"
