definitions:
  model.Registration:
    properties:
      confirm:
        type: string
      name:
        type: string
      passwd:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/waf/host:
    post:
      consumes:
      - application/json
      parameters:
      - description: registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.Registration'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: user sign up
      tags:
      - auth
swagger: "2.0"
